name: AutoPdfPreview
on:
  push:
    branches: [ "main" ]
  # Allows me to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mkpdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Make LaTex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./doc/**/*.tex
      
      - name: Preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv *.pdf ../
          git config user.email "script@no.email.com"
          git config user.name "script"
          git fetch origin preview
          git checkout preview
          mv -f ../*.pdf .
          git add ./\*.pdf
          git commit -m 'auto preview' || true
          git push origin preview || true
